dbt_coinbase:
  outputs:
    dev:
      dataset: coinbase_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/key.json
      location: US
      method: service-account
      priority: interactive
      project: crypto-data-pipeline-477720
      threads: 1
      type: bigquery
  target: dev
